# Generated by Django 3.0.6 on 2020-05-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('pages', models.IntegerField(verbose_name='Número de Páginas')),
                ('code', models.IntegerField(verbose_name='Código')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.Author')),
            ],
        ),
    ]
